# Generated by Django 6.0 on 2025-12-28 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_options_alter_tags_options_post_cody'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cody',
            new_name='code',
        ),
    ]
