# Generated by Django 6.0 on 2026-01-03 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_replies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.post'),
        ),
    ]
