# Generated by Django 6.0 on 2026-01-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_notification_options_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
