# Generated by Django 6.0 on 2025-12-28 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_control', '0002_alter_customuser_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='technologies',
            options={'verbose_name': 'Technology', 'verbose_name_plural': 'Technologies'},
        ),
    ]
