# Generated by Django 6.0 on 2025-12-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_control', '0003_alter_customuser_options_alter_technologies_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
