# Generated by Django 6.0 on 2026-01-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_control', '0004_customuser_github_link_customuser_linkedin_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
