# Generated by Django 6.0 on 2026-01-06 03:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_control', '0006_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
