# Generated by Django 6.0 on 2026-01-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_control', '0008_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_vip',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
